//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models.Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPersonel
    {
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> SehirID { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public int id { get; set; }
        public int DepartmanID { get; set; }
        public Nullable<int> CinsiyetID { get; set; }
    
        public virtual TblCinsiyet TblCinsiyet { get; set; }
        public virtual TblDepartman TblDepartman { get; set; }
        public virtual TblSehir TblSehir { get; set; }
    }
}
